AntHurry/AntHurry

src/main/java/com/ant/hurry/base/home/HomeController.java
src/main/resources/static/resource/common/common.css
src/main/resources/templates/common/navbar.html
src/main/resources/templates/error/404.html
src/main/resources/templates/home/main.html

layout, navbar 파일을 따로 만들었습니다.
/main으로 접속했을 때 기본 레이아웃이 반영되지 않아서 일단 home/main.html에 기본 레이아웃 내용을 모두 넣어서 작성했습니다. /main으로 접속하시면 되고, 검사 > Dimentions : iphone 12 pro로 확인하시면 됩니다.
상단 navbar는 페이지마다 내용이 다를 거 같아서 기본 레이아웃으로 빼지 않고 main의 내용으로 넣어놨으니 참고 부탁드립니다.
close #7

feature/layout: 기본 레이아웃 html 파일 작성

---

src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/board/entity/Board.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/resources/static/resource/common/common.css
src/main/resources/templates/board/create.html

현재 게시글 작성 페이지 폼만 만들었습니다. 1차적인 디자인이라서 미흡합니다. 나중에 추가적으로 디자인 수정하겠습니다.

style: 게시글 작성 페이지

---

src/main/java/com/ant/hurry/boundedContext/notification/controller/NotificationController.java
src/main/java/com/ant/hurry/boundedContext/notification/entity/Notification.java
src/main/java/com/ant/hurry/boundedContext/notification/entity/NotifyType.java
src/main/java/com/ant/hurry/boundedContext/notification/repository/NotificationRepository.java
src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/resources/templates/notification/list.html
src/test/java/com/ant/hurry/boundedContext/notification/controller/NotificationControllerTest.java
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

알림 목록 페이지 구현했습니다.
Notification Entity에 type 필드가 필요해서 Enum 타입의 필드를 하나 추가했습니다.
확인부탁드립니다~
close #22

Feature/notification: 알림 목록 페이지 구현

---

src/main/resources/templates/common/layout.html
src/main/resources/templates/error/404.html
src/main/resources/templates/usr/home/main.html
src/main/resources/templates/usr/member/login.html

Feature/404: 404 page custom, 상단 내비바 고정

---

src/main/java/com/ant/hurry/base/region/service/RegionSearchService.java
src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/resources/templates/board/enterRegion.html
src/main/resources/templates/board/region.html
src/main/resources/templates/board/selectRegion.html
src/main/resources/templates/usr/layout/layout.html
src/test/java/com/ant/hurry/base/region/service/RegionSearchServiceTest.java
src/test/java/com/ant/hurry/boundedContext/board/controller/BoardControllerTests.java

Feature/select region: 지역 검색 및 게시판 진입

---

src/main/resources/application.yml
src/main/resources/templates/usr/member/login.html

* 네이버 로그인
* application.yml 에 네이버 로그인 추가
* login.html 에 네이버 로그인 링크 추가
* application-secret.yml 에 api key 설정 해야됩니다.

Feat/naver login : 네이버 로그인

---

src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
src/main/resources/templates/usr/member/profile.html

Feature/profile UI: 프로필 UI 

---

src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
src/main/resources/data_h2.sql
src/main/resources/templates/tradeStatus/list.html
src/test/java/com/ant/hurry/boundedContext/review/controller/ReviewControllerTest.java
src/test/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusControllerTest.java
src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java

- 거래 상태 목록 기능 구현
- 거래 상태 목록 레이아웃 구현
- 거래 상태 목록 상태 전환 비동기 처리
- 거래 상태 목록 테스트 코드 작성
close #35

Feature/trade status: 거래 상태 페이지 구현

---

src/main/java/com/ant/hurry/boundedContext/notification/controller/NotificationController.java
src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/resources/data_h2.sql
src/main/resources/templates/notification/list.html
src/test/java/com/ant/hurry/boundedContext/notification/controller/NotificationControllerTest.java
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

- 알림 메시지 구체적으로 변경
- 알림 삭제 기능 구현
- 알림 목록 레이아웃 수정
close #64

Feature/notification: 알림 삭제 기능 추가 및 레이아웃 수정

---

src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/resources/data_h2.sql
src/main/resources/templates/board/enterRegion.html
src/test/java/com/ant/hurry/boundedContext/board/controller/BoardControllerTests.java

게시판 - ex) 역삼동이면 역삼동의 게시물들만 볼 수 있다.
맨 처음에는 -> 모든 게시물들 나열
나 급해요 클릭시 -> 나 급해요 게시물만 보여줌
나 잘해요 클릭시 -> 나 잘해요 게시물만 보여줌
resolve #60

Feature/board list: 해당 동네의 게시판의 게시글 확인 및 나급해요/나잘해요 버튼으로 구별

---

src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java

feat: stream -> jpa: 리팩토링

---

src/main/java/com/ant/hurry/base/initData/DataLoader.java
src/main/resources/data_h2.sql

CommandLineRunner를 통해 실행 시 관리자 계정을 자동으로 생성하도록 만들었습니다.
close #68

Feature/admin: 실행 시 관리자 계정 생성 

---

src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/resources/data_h2.sql
src/main/resources/templates/notification/list.html
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

- 알림 목록 레이아웃 수정
- 알림 메시지 수정 (거래 파기 -> 거래 취소)
- 알림 메시지 테스트 코드 추가
close #73

Feature/notification: 알림 메시지 및 레이아웃 수정

---

src/main/java/com/ant/hurry/base/code/BasicErrorCode.java
src/main/java/com/ant/hurry/chat/code/ChatMessageSuccessCode.java
src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
src/main/java/com/ant/hurry/chat/code/ChatRoomSuccessCode.java
src/test/java/com/ant/hurry/chat/repository/ChatMessageRepositoryTest.java
src/test/java/com/ant/hurry/chat/repository/ChatRoomRepositoryTest.java
src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
src/test/java/com/ant/hurry/chat/service/ChatRoomServiceTest.java

기존에 @AfterEach만 있었을 때 deleteAll 메서드가 실행이 제대로 안 되어 실패하는 경우가 있었는데, @BeforeEach, @AfterAll로 변경해주니 제대로 동작합니다. 혹시나 또 테스트 실패하면 디스코드로 말씀해주시면 감사하겠습니다 ㅠㅠ

Feature/chatting: 채팅 관련 테스트 수정

---

src/main/java/com/ant/hurry/base/initData/DataLoader.java
src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/board/dto/CreateRequest.java
src/main/java/com/ant/hurry/boundedContext/board/entity/Board.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/resources/data_h2.sql
src/main/resources/templates/board/board.html
src/main/resources/templates/board/modify.html
src/main/resources/templates/common/layout.html
src/main/resources/templates/usr/home/main.html
src/main/resources/templates/usr/member/login.html

- 게시판 수정할 때 주소 부분을 그대로 두면 유지, 수정시에 주소 변동
- 코인도 수정시에 변동
- 카카오 API를 사용해서 depth3 를 가져올 경우 가끔 00면 00리 와 같이 두 가지를 가져올 때가 있어서 에러가 발생하여 필요한 부분만을 추출
resolve #70

Feature/modify board: 게시판 수정, kakao API 오류 수정

---

src/main/resources/templates/common/layout.html
src/main/resources/templates/usr/member/usrCheck.html

이미지 크기가 h-40인데 h-36도 괜찮더라고요! 
resolve #86

feature/usrProfileCheck: 상대방 프로필 확인 UI

---

src/main/java/com/ant/hurry/base/s3/S3ProfileUploader.java
src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
src/main/java/com/ant/hurry/boundedContext/member/dto/ProfileRequestDto.java
src/main/java/com/ant/hurry/boundedContext/member/service/MemberService.java
src/main/resources/templates/usr/member/phone_auth.html
src/main/resources/templates/usr/member/profile_edit.html

* 전화번호 인증 페이지 UI 변경
* 프로필 수정 페이지 UI 변경 및 Ajax 코드로 변경
* 닉네임에 대한 유효성 검사를 JS 로 변경했습니다.
close #56

Style/UI improvement : ui 개선

---

src/main/java/com/ant/hurry/boundedContext/member/service/MemberService.java
src/main/java/com/ant/hurry/boundedContext/review/controller/ReviewController.java
src/main/java/com/ant/hurry/boundedContext/review/dto/ReviewRequest.java
src/main/java/com/ant/hurry/boundedContext/review/entity/Review.java
src/main/java/com/ant/hurry/boundedContext/review/repository/ReviewRepository.java
src/main/java/com/ant/hurry/boundedContext/review/service/ReviewService.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/resources/data_h2.sql
src/main/resources/static/resource/common/star.css
src/main/resources/templates/review/create.html
src/main/resources/templates/review/list.html
src/main/resources/templates/tradeStatus/list.html
src/main/resources/templates/usr/member/profile.html
src/test/java/com/ant/hurry/boundedContext/review/controller/ReviewControllerTest.java
src/test/java/com/ant/hurry/boundedContext/review/service/ReviewServiceTest.java

- rating 소수점 첫째자리까지 표시 및 마이페이지에 별점 표시
- 거래 상태 목록 페이지 수정
- 후기 목록 페이지 로직 수정 (내가 받은 후기만 보이게 수정)
- 후기 등록 안되던 부분 수정 (Request 객체에 @Setter 추가)

Feature/review: 후기 작성 및 목록 리팩토링

---

src/test/java/com/ant/hurry/boundedContext/board/controller/BoardControllerTest.java
src/test/java/com/ant/hurry/boundedContext/board/service/BoardServiceTest.java

feature/modifyTest: 게시글 수정 테스트

---

src/main/java/com/ant/hurry/base/home/HomeController.java
src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/resources/templates/board/enterRegion.html
src/main/resources/templates/board/online.html
src/main/resources/templates/usr/home/main.html

일단 무한 스크롤 적용 전에 예시로 만들어 두었습니다.
resolve #88

Feature/search writing: 온라인 게시글 검색

---

src/main/java/com/ant/hurry/base/security/SecurityConfig.java
src/main/java/com/ant/hurry/boundedContext/board/entity/Board.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepository.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/java/com/ant/hurry/boundedContext/review/service/ReviewService.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusErrorCode.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/code/TradeStatusSuccessCode.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
src/main/java/com/ant/hurry/chat/baseEntity/BaseMessage.java
src/main/java/com/ant/hurry/chat/baseEntity/Message.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
src/main/java/com/ant/hurry/chat/entity/Message.java
src/main/java/com/ant/hurry/chat/repository/ChatMessageRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
src/main/resources/templates/board/board.html
src/main/resources/templates/chat/room.html
src/test/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusControllerTest.java
src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
src/test/java/com/ant/hurry/chat/controller/ChatRoomControllerTest.java

채팅 관련한 모든 코드를 리팩토링했습니다.
TradeStatus의 create 메서드를 제대로 구현하고, chatRoom으로 redirect되도록 설정했습니다.
html에 채팅이 작동될 수 있도록 코드를 작성하긴 했지만 웹소켓 연결이 안 되어서 메시지가 제대로 보내지는지는 확인하지 못했습니다... 채팅하기 버튼을 누르면 새로 생성된 채팅방으로 정상적으로 redirect되는 것까진 확인했습니다!
채팅 기능을 본격적으로 구현하기 전에도 웹소켓 연결이 실패했었는데, 그때는 SecurityConfig에 http.authorizeHttpRequests(); 를 추가했더니 되었기에 이번에도 한번 넣어봤습니다. 그치만 여전히 연결이 안 되는 상태입니다 ㅠㅠㅠㅠ
수정한 파일이 많아서 기능이 제대로 작동하기 전에 PR 생성하니 참고 부탁드립니다.
close #82

Feature/connectChat: 채팅 관련 전체 코드 리팩토링 및 TradeStatus-ChatRoom 연결, html 수정

---

build.gradle
src/main/java/com/ant/hurry/base/security/SecurityConfig.java
src/main/java/com/ant/hurry/chat/config/StompWebSocketConfig.java
src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
src/main/java/com/ant/hurry/chat/dto/ChatMessageDto.java
src/main/java/com/ant/hurry/chat/entity/ChatMessage.java
src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
src/main/resources/templates/chat/room.html
src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java

몽고 디비 임베디드 테스트 관련 디펜던시와 GridFs 디펜던시를 없앴습니다. 없애도 문제 없더라구요!
또한 웹소켓 연결이 성공해서 수정 필요한 부분 수정 진행했고, 메시지가 잘 보내지는지 확인했습니다.
화면에 제대로 뜨지는 않아서 코드 수정이 더 필요할 것 같습니다.

Feature/chatting: 필요없는 디펜던시 제거, 채팅 관련 리팩토링

---

src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
src/main/resources/data_h2.sql
src/main/resources/templates/common/layout.html
src/main/resources/templates/usr/member/faq.html
src/main/resources/templates/usr/member/profile.html

feature/faq: 프로필 페이지에 faq 추가했습니다.

---

src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
src/main/java/com/ant/hurry/chat/repository/ChatRoomRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepositoryImpl.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/resources/templates/chat/myRooms.html
src/main/resources/templates/chat/room.html
src/test/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusServiceTest.java
src/test/java/com/ant/hurry/chat/controller/ChatRoomControllerTest.java
src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java

데일리 스크럼 때 말씀드린 대로 모달창 버튼 클릭 시 거래 상태가 제대로 변경될 수 있도록 수정했습니다.
채팅방 나가기 기능도 구현했고, 채팅방에서 파일을 보낼 수 있도록 html도 수정했습니다.
실제로 파일을 전송하는 로직과 다운로드하는 로직은 수정이 많이 필요할 듯하여 미리 PR 올리니 참고 부탁드립니다!

Feature/chatting: 거래 상태 변경, 채팅방 나가기 기능 구현

---

src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
src/main/resources/templates/board/board.html

fix: 게시판 상세정보 오류 수정 (#104)

---

src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java
src/main/resources/templates/board/board.html

feat: 게시판 상세정보에서 채팅 redirect (#132)

---

src/main/java/com/ant/hurry/base/initData/DataLoader.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
src/main/java/com/ant/hurry/chat/entity/LatestMessage.java
src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
src/main/resources/templates/chat/myRooms.html
src/main/resources/templates/chat/room.html

빌드할 때 몽고 디비 데이터가 초기화될 수 있도록 코드를 추가했습니다.
또한 채팅 로직에서 멤버의 닉네임이 사용되는 부분을 모두 유저네임으로 변경했습니다.
상대방이 채팅방을 나갔을 때 채팅 목록에서 오류가 발생한 부분은 테스트를 아직 안 해봐서 확인해봐야 될 것 같습니다.

Feature/chatting: 빌드 시 몽고 디비 초기화 및 닉네임 -> 유저네임으로 수정

---

build.gradle
src/main/java/com/ant/hurry/base/jasypt/JasyptConfig.java
src/main/java/com/ant/hurry/base/security/SecurityConfig.java
src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/java/com/ant/hurry/chat/entity/ChatFileMessage.java
src/main/java/com/ant/hurry/chat/repository/ChatFileMessageRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepositoryImpl.java
src/main/java/com/ant/hurry/chat/service/ChatMessageService.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/resources/application.yml
src/main/resources/templates/chat/myRooms.html
src/main/resources/templates/chat/room.html
src/test/java/com/ant/hurry/chat/repository/ChatMessageRepositoryTest.java
src/test/java/com/ant/hurry/chat/repository/ChatRoomRepositoryTest.java
src/test/java/com/ant/hurry/chat/service/ChatMessageServiceTest.java
src/test/java/com/ant/hurry/chat/service/ChatRoomServiceTest.java

채팅 메시지를 통해 파일을 다운로드할 수 있습니다.
자잘하게 수정한 부분은 테스트 어노테이션을 변경했고, 채팅 목록에서도 상대방의 닉네임이 길 때 'user1234... 님' 이런 식으로 줄여져서 보이게 처리했습니다.
또한 채팅 메시지를 보낼 때 상단부터 차곡차곡 쌓이도록 수정했습니다.
상대방이 채팅방을 나가면 아래와 같이 알림 메시지가 전송됩니다.
아직 채팅방 나가기 기능 후에 오류가 뜨는 부분은 못 잡았습니다 ㅠㅠ
close #117

Feature/chatting: 채팅 메시지로 파일 다운로드 받을 수 있도록 구현 & Jasypt 적용

---

src/main/java/com/ant/hurry/base/rq/Rq.java
src/main/java/com/ant/hurry/boundedContext/notification/controller/NotificationController.java
src/main/java/com/ant/hurry/boundedContext/notification/entity/Notification.java
src/main/java/com/ant/hurry/boundedContext/notification/entity/NotifyType.java
src/main/java/com/ant/hurry/boundedContext/notification/event/NotifyStartMessageEvent.java
src/main/java/com/ant/hurry/boundedContext/notification/event/handler/NotificationEventHandler.java
src/main/java/com/ant/hurry/boundedContext/notification/repository/NotificationRepository.java
src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/resources/templates/chat/room.html
src/main/resources/templates/usr/layout/layout.html
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

- 거래 시작 알림 기능 추가
- 채팅 시작 및 거래 상태 변경 시 알림 이벤트(알림 및 sms 생성) 발생하도록 설정 
- 거래 취소 상태일 때 채팅방 모달창에 '채팅방 나가기'만 보이도록 수정
- 알림 읽음 기능 추가
- 읽지 않은 알림이 있을 경우 내비게이션 바 알림창에 표시 (indicator)
close #137

Feature/notification: 알림 연결 작업 및 읽음 기능 추가

---

src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/java/com/ant/hurry/chat/service/LatestMessageService.java
src/main/resources/templates/chat/myRooms.html

채팅방 나가기에 대한 로직을 수정했습니다. 디버깅해보니 member 객체가 프록시 객체로 잡혀서 나가기가 제대로 안 되었던 거였습니다!
new 인디케이터도 채팅을 읽으면 사라지도록 제대로 구현했습니다.
close #146

Feature/chat: 채팅방 나가기 로직 수정

---

src/main/java/com/ant/hurry/base/region/initData/initRegion.java
src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/chat/entity/ChatRoom.java
src/main/java/com/ant/hurry/chat/repository/ChatRoomRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepository.java
src/main/java/com/ant/hurry/chat/repository/CustomChatRoomRepositoryImpl.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/resources/templates/chat/myRooms.html
src/main/resources/templates/chat/room.html

노션의 이슈에 적힌 채팅방 관련 기능 오류를 수정했습니다.

Feature/chat: 채팅방 관련 기능 오류 수정

---

src/main/java/com/ant/hurry/boundedContext/notification/event/NotifyCancelMessageEvent.java
src/main/java/com/ant/hurry/boundedContext/notification/event/NotifyEndMessageEvent.java
src/main/java/com/ant/hurry/boundedContext/notification/event/NotifyStartMessageEvent.java
src/main/java/com/ant/hurry/boundedContext/notification/event/handler/NotificationEventHandler.java
src/main/java/com/ant/hurry/boundedContext/notification/repository/NotificationRepository.java
src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/resources/templates/notification/list.html
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

Notification 객체를 두 개 생성해서 requester와 helper에게 다르게 메시지가 보이도록 수정했습니다.

Feature/notification: 알림 메시지 두명에게 다르게 보이도록 수정

---

src/main/java/com/ant/hurry/chat/service/ChatMessageService.java

채팅방을 나갔을 때 전송되는 알림 메시지가 latestMessageRepository에도 저장되도록 했습니다.

Feature/chat: 알림 메시지가 latestMessage에도 저장되도록 수정

---

src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/repository/TradeStatusRepository.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/service/TradeStatusService.java

- 거래 완료 되면 채팅하기 눌렀을 때 거래 생성 안되게 만들기
- 거래 완료 되면 나머지 사람들 거래 취소 상태로 바뀌게 만들기
- 거래 완료 되면 다른 사람들은 거래 완료 못 누르게 바꾸기
close #159

Fix/tradeStatus: 거래 완료에 따른 로직 추가

---

src/main/java/com/ant/hurry/boundedContext/notification/entity/Notification.java
src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/resources/templates/notification/list.html
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

Feature/afterreview: 알림창에서 helper는 리뷰 작성 할 수 있도록 했습니다.

---

src/main/java/com/ant/hurry/base/security/SecurityConfig.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/resources/templates/chat/room.html

Fix/chat: 채팅 목록 정렬 및 채팅방에서 상대방 프로필 조회

---

src/main/java/com/ant/hurry/base/security/SecurityConfig.java
src/main/java/com/ant/hurry/boundedContext/board/controller/BoardController.java
src/main/resources/data_h2.sql
src/main/resources/templates/board/enterRegion.html
src/main/resources/templates/board/online.html
src/main/resources/templates/board/search.html
src/main/resources/templates/usr/member/login.html

- 동네 게시판에서 검색할 때 한 글자만 쓰면 에러나는 문제 해결했습니다.
- 검색 내용 없을 시에 '내용'이 없다고 나타내었습니다.
- 로그인창에도 faq 추가했습니다.
resolve #175

Fix/board and faq: 동네 게시판에서 검색할 때 두 글자 이상 되도록, 검색 내용이 없을 경우, faq

---

src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepositoryCustom.java
src/main/java/com/ant/hurry/boundedContext/board/repository/BoardRepositoryImpl.java
src/main/java/com/ant/hurry/boundedContext/board/service/BoardService.java
src/main/java/com/ant/hurry/boundedContext/member/controller/MemberController.java
src/main/resources/data_h2.sql
src/main/resources/templates/usr/member/myboard.html
src/main/resources/templates/usr/member/profile.html

프로필 페이지에서 내 게시글 확인할 수 있도록 했습니다.
resolve #182

Feature/myboard: 내 게시글 확인 

---

src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/main/java/com/ant/hurry/chat/code/ChatRoomErrorCode.java
src/main/java/com/ant/hurry/chat/code/ChatRoomSuccessCode.java
src/main/java/com/ant/hurry/chat/controller/ChatMessageController.java
src/main/java/com/ant/hurry/chat/controller/ChatRoomController.java
src/main/java/com/ant/hurry/chat/service/ChatRoomService.java
src/main/resources/templates/board/search.html
src/main/resources/templates/chat/myRooms.html
src/main/resources/templates/chat/room.html
src/test/java/com/ant/hurry/chat/service/ChatRoomServiceTest.java

Fix/chat: 채팅 퇴장 및 재입장 로직 수정, html 일부 수정

---

src/main/java/com/ant/hurry/boundedContext/notification/service/NotificationService.java
src/main/java/com/ant/hurry/boundedContext/tradeStatus/controller/TradeStatusController.java
src/test/java/com/ant/hurry/boundedContext/notification/service/NotificationServiceTest.java

Fix/notification 채팅 시작 시, SMS
